### ISSUE TITLE
 packages ml_collections, einops and monai aren't declared  in setup.py

### ISSUE THREAD

**Issue by yeyeyeping** [HiLab-git/PyMIC#39]
nice work!
PyMIC seems to have dependencies on  `ml_collections`, `einops`,`monai` , but these packages aren't declared in setup.py. Someone who use `PyMIC` may  still need to  run `pip install ml_collections einops monai` even after `pip install pymic`.

```
(pymic) ➜  ~ pip list |grep -i "pymic"
PYMIC                   0.4.0
(pymic) ➜  ~ pymic_train /home/yeep/project/py/sph/sph2d/unet.cfg
Traceback (most recent call last):
  File "/home/yeep/env/miniconda/envs/pymic/bin/pymic_train", line 5, in <module>
    from pymic.net_run.train import main
  File "/home/yeep/env/miniconda/envs/pymic/lib/python3.9/site-packages/pymic/net_run/train.py", line 10, in <module>
    from pymic.net_run.agent_seg import SegmentationAgent
  File "/home/yeep/env/miniconda/envs/pymic/lib/python3.9/site-packages/pymic/net_run/agent_seg.py", line 20, in <module>
    from pymic.net.net_dict_seg import SegNetDict
  File "/home/yeep/env/miniconda/envs/pymic/lib/python3.9/site-packages/pymic/net/net_dict_seg.py", line 24, in <module>
    from pymic.net.net2d.trans2d.transunet import TransUNet
  File "/home/yeep/env/miniconda/envs/pymic/lib/python3.9/site-packages/pymic/net/net2d/trans2d/transunet.py", line 15, in <module>
    import pymic.net.net2d.trans2d.transunet_cfg as configs
  File "/home/yeep/env/miniconda/envs/pymic/lib/python3.9/site-packages/pymic/net/net2d/trans2d/transunet_cfg.py", line 4, in <module>
    import ml_collections
ModuleNotFoundError: No module named 'ml_collections'
```

**Comment by mehrnia** [comment]
I noticed the same thing
