### ISSUE TITLE
ImportError: cannot import name 'TaskType' from 'pymic'

### ISSUE THREAD

**Issue by TimeChanged** [HiLab-git/PyMIC#41]
Sorry to bother.

I use pip install PYMIC for the latest 0.4.0 version.
And use it to run projects using pymic but have this issue.
together with something else, seems like I can't use

To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "f:\ISY5001\task\MIS-FM-main\predict.py", line 10, in <module>
    from pymic.net_run.agent_seg import SegmentationAgent
  File "E:\software\anaconda3\Lib\site-packages\pymic\net_run\agent_seg.py", line 20, in <module> 
    from pymic.net.net_dict_seg import SegNetDict
    import pymic.net.net2d.trans2d.transunet_cfg as configs
  File "E:\software\anaconda3\Lib\site-packages\pymic\net\net2d\trans2d\transunet_cfg.py", line 4, in <module>
    import ml_collections
ModuleNotFoundError: No module named 'ml_collections'

How can I solve that?

**Comment by chenyucong1** [comment]
Hello, I have the same problem
“ from pymic import TaskType
ImportError: cannot import name 'TaskType' from 'pymic' ”

**Comment by taigw** [comment]
Hello, the problem has been fixed, and you can try the latest version of PyMIC by installing PyMIC from the dev branch (download the source code and use `python setup.py install`). We will also include it into the master branch and released version soon.
